# benchmark config yaml
### Please fill these accordingly
data_dir: /raid/gpu-bdb/sf1000/parquet_2gb/
output_dir: /raid/nicholasb/gpu-bdb-results/sf1000
file_format: parquet
output_filetype: parquet
split_row_groups: False
repartition_small_table: True
benchmark_runner_include_bsql: False

scheduler_file_path: /raid/nicholasb/dask-local-directory/scheduler.json
dask_profile: False
dask_dir: ./
num_workers: 16

verify_results: False
verify_dir: 

sheet: TPCx-BB
tab: SF1000 Benchmarking Matrix
get_read_time: False
